### PR TITLE
#1 Fix InvalidCastException

### PR DESCRIPTION
**Pull request by wangzq**

### CODE REVIEW

**Comment by citizenmatt** [comment]
Thanks for the PR! Do you have an example where this causes an issue? Internally, ReSharper stores this value as an `int`, and the values are deserialised from XAML, so it should already be an int, and casting should be fine. ("Should" is the key word there :smile: )

**Comment by citizenmatt** [comment]
Actually, my bad. It's internally an int, but serialised as a long.

**Comment by citizenmatt** [comment]
I've merged the changes - thanks!

I'd still be interested of an example that causes an issue, if you've got one.

**Comment by wangzq** [comment]
I have attached a DotSettings file with just one live template that can
reproduce this issue. You are right that not every template will have such
issue, I tried and isolated this specific template that will reproduce the
issue.

**Comment by wangzq** [comment]
https://github.com/wangzq/resharper-template-compiler/blob/master/LiveTemplates.DotSettings

**Pull request merged**
